services:
  postgres:
    image: postgres:17
    container_name: zt-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:8-alpine
    container_name: zt-redis
    ports:
      - "6379:6379"
    volumes:
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  minio:
    image: minio/minio
    container_name: zt-minio
    env_file:
      - .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  gateway-api:
    build: ./apps/gateway-api
    container_name: zt-gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  auth-service:
    build: ./apps/auth-service
    container_name: zt-auth
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis

  policy-service:
    build: ./apps/policy-service
    container_name: zt-policy
    env_file:
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - postgres

  file-service:
    build: ./apps/file-service
    container_name: zt-file
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      - postgres
      - minio

  audit-service:
    build: ./apps/audit-service
    container_name: zt-audit
    env_file:
      - .env
    ports:
      - "8004:8000"
    depends_on:
      - postgres

  alert-service:
    build: ./apps/alert-service
    container_name: zt-alert
    env_file:
      - .env
    ports:
      - "8006:8000"
    depends_on:
      - postgres

  risk-service:
    build: ./apps/risk-service
    container_name: zt-risk
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - postgres
      - redis
      - minio
      - audit-service
      - alert-service

  worker-service:
    build: ./apps/worker-service
    container_name: zt-worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - minio

  frontend:
    build: ./apps/frontend
    container_name: zt-frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - gateway-api

volumes:
  postgres_data:
  minio_data: